language: c
compiler: gcc
addons:
        apt:
                packages:
                  - check
                  - splint
                  # for "make rpm"
                  - doxygen
                  - rpm
script: RPMBUILDOPTS_="--nodeps --define '_without_check 1'";
        ./autogen.sh
        && ./configure --enable-syslog-tests
        && make check
        && make distcheck
        && sed "s|RPMBUILDOPTS =|\\0 ${RPMBUILDOPTS_}|" Makefile | make -f- rpm
sudo: false

notifications:
        irc: "irc.freenode.net#clusterlabs-dev"
