language: c
compiler: gcc
addons:
        apt:
                packages:
                  - check
                  - splint
script: ./autogen.sh
        && ./configure --enable-syslog-tests
        && make
        && make check
        && make distcheck
sudo: false

notifications:
        irc: "irc.freenode.net#clusterlabs-dev"
