language: c
compiler:
        - gcc
        - clang
addons:
        apt:
                sources:
                        - debian-sid
                packages:
                        - check
                        - splint
                        - rpmlint
                        # for "make rpm"
                        - doxygen
                        - rpm
script: RPMBUILDOPTS_="--nodeps --define '_without_check 1'";
        ./autogen.sh
        && ./configure
        && DISTCHECK_CONFIGURE_FLAGS=--enable-syslog-tests VERBOSE=1 make distcheck
        && sed "s|RPMBUILDOPTS =|\\0 ${RPMBUILDOPTS_}|" Makefile | make -f- rpm
        && rpmlint -iv libqb.spec
sudo: false

notifications:
        irc: "irc.freenode.net#clusterlabs-dev"
