language: c
compiler: gcc
addons:
        apt:
                packages:
                  - check
                  - splint
script: ./autogen.sh
        && ./configure --enable-syslog-tests
        && make check
        && make distcheck
sudo: false
