sudo: false
language: c
compiler:
        - gcc
        - clang
addons:
        apt:
                packages:
                        - check
                        - splint
                        # for ipc.test:test_ipc_dispatch_*_deadlock_provoke
                        - libglib2.0-dev  # natively present, but doesn't hurt
                        # for "make rpm"
                        - doxygen
                        - rpm

script: RPMBUILDOPTS_="--nodeps --define '_without_check 1'";
        ./autogen.sh
        && ./configure
        && make -C lib V=1
        && make -C tests/functional/log_internal V=1 check
        && make V=1 CPPFLAGS=-Dci_dump_shm_usage distcheck
        && sed "s|RPMBUILDOPTS =|\\0 ${RPMBUILDOPTS_}|" Makefile | make -f- rpm

after_failure:
        # keep an eye on issue #234 if it recidivates
        - for f in $(ls -1 /dev/shm/qb-test*); do ls -l "$f"; lsof -- "$f"; done
        #- ls -l /var/run/*
        - mount | grep -e /shm  #-e /var
        - df -h | grep -e /shm  #-e /var
        - lsblk -f
        - cat /tmp/_shm_usage

notifications:
        irc: "irc.freenode.net#clusterlabs-dev"
