#!/bin/sh
#
# This is a copy of the linux kernel's Lindent because
# we use the same formatting. No point re-inventing that
# wheel.
#
# Differences to kernel style:
# --dont-break-procedure-type -> --break-procedure-type
#
PARAM="-npro -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4
-cli0 -d0 -di1 -nfc1 -i8 -ip0 -l80 -lp -npcs -nprs -psl -sai
-saf -saw -ncs -nsc -sob -nfca -cp1 -ss -ts8"
RES=`indent --version`
V1=`echo $RES | cut -d' ' -f3 | cut -d'.' -f1`
V2=`echo $RES | cut -d' ' -f3 | cut -d'.' -f2`
V3=`echo $RES | cut -d' ' -f3 | cut -d'.' -f3`
if [ $V1 -gt 2 ]; then
	PARAM="$PARAM -il0"
elif [ $V1 -eq 2 ]; then
	if [ $V2 -gt 2 ]; then
		PARAM="$PARAM -il0";
	elif [ $V2 -eq 2 ]; then
		if [ $V3 -ge 10 ]; then
			PARAM="$PARAM -il0"
		fi
	fi
fi
indent $PARAM "$@"

